# 机器人血量数据 (裁判系统串口协议 V1.7.0 0x0003)

uint16 red_1_robot_hp       # 红 1 英雄机器人血量。若该机器人未上场或者被罚下，则血量为 0
uint16 red_2_robot_hp       # 红 2 工程机器人血量
uint16 red_3_robot_hp       # 红 3 步兵机器人血量
uint16 red_4_robot_hp       # 红 4 步兵机器人血量
uint16 red_7_robot_hp       # 红 7 哨兵机器人血量
uint16 red_outpost_hp       # 红方前哨站血量
uint16 red_base_hp          # 红方基地血量
uint16 blue_1_robot_hp      # 蓝 1 英雄机器人血
uint16 blue_2_robot_hp      # 蓝 2 工程机器人血量
uint16 blue_3_robot_hp      # 蓝 3 步兵机器人血量
uint16 blue_4_robot_hp      # 蓝 4 步兵机器人血量
uint16 blue_7_robot_hp      # 蓝 7 哨兵机器人血量
uint16 blue_outpost_hp      # 蓝方前哨站血量
uint16 blue_base_hp         # 蓝方基地血量
